/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelPeriodPropertyLinkWithValue {
    ApimodelPeriodTextPropertyLinkValue(Box<models::ApimodelPeriodTextPropertyLinkValue>),
    ApimodelPeriodNumberPropertyLinkValue(Box<models::ApimodelPeriodNumberPropertyLinkValue>),
    ApimodelPeriodSelectPropertyLinkValue(Box<models::ApimodelPeriodSelectPropertyLinkValue>),
    ApimodelPeriodMultiSelectPropertyLinkValue(Box<models::ApimodelPeriodMultiSelectPropertyLinkValue>),
    ApimodelPeriodDatePropertyLinkValue(Box<models::ApimodelPeriodDatePropertyLinkValue>),
    ApimodelPeriodFilesPropertyLinkValue(Box<models::ApimodelPeriodFilesPropertyLinkValue>),
    ApimodelPeriodCheckboxPropertyLinkValue(Box<models::ApimodelPeriodCheckboxPropertyLinkValue>),
    ApimodelPeriodUrlPropertyLinkValue(Box<models::ApimodelPeriodUrlPropertyLinkValue>),
    ApimodelPeriodEmailPropertyLinkValue(Box<models::ApimodelPeriodEmailPropertyLinkValue>),
    ApimodelPeriodPhonePropertyLinkValue(Box<models::ApimodelPeriodPhonePropertyLinkValue>),
    ApimodelPeriodObjectsPropertyLinkValue(Box<models::ApimodelPeriodObjectsPropertyLinkValue>),
}

impl Default for ApimodelPeriodPropertyLinkWithValue {
    fn default() -> Self {
        Self::ApimodelPeriodTextPropertyLinkValue(Default::default())
    }
}

