/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelAddObjectsToListRequest {
    /// The list of object IDs to add to the list
    #[serde(rename = "objects", skip_serializing_if = "Option::is_none")]
    pub objects: Option<Vec<String>>,
}

impl ApimodelAddObjectsToListRequest {
    pub fn new() -> ApimodelAddObjectsToListRequest {
        ApimodelAddObjectsToListRequest {
            objects: None,
        }
    }
}

