/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelCreateChallengeRequest {
    /// The name of the app that is requesting the challenge
    #[serde(rename = "app_name", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
}

impl ApimodelCreateChallengeRequest {
    pub fn new() -> ApimodelCreateChallengeRequest {
        ApimodelCreateChallengeRequest {
            app_name: None,
        }
    }
}

