/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelCreateTagRequest {
    #[serde(rename = "color")]
    pub color: models::ApimodelColor,
    /// The name of the tag
    #[serde(rename = "name")]
    pub name: String,
}

impl ApimodelCreateTagRequest {
    pub fn new(color: models::ApimodelColor, name: String) -> ApimodelCreateTagRequest {
        ApimodelCreateTagRequest {
            color,
            name,
        }
    }
}

