/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodObjectResponse {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Box<models::ApimodelPeriodObjectWithBody>>,
}

impl ApimodelPeriodObjectResponse {
    pub fn new() -> ApimodelPeriodObjectResponse {
        ApimodelPeriodObjectResponse {
            object: None,
        }
    }
}

