/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelCreateChallengeResponse {
    /// The challenge id associated with the displayed code and needed to solve the challenge for api_key
    #[serde(rename = "challenge_id", skip_serializing_if = "Option::is_none")]
    pub challenge_id: Option<String>,
}

impl ApimodelCreateChallengeResponse {
    pub fn new() -> ApimodelCreateChallengeResponse {
        ApimodelCreateChallengeResponse {
            challenge_id: None,
        }
    }
}

