/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelCreateApiKeyRequest {
    /// The challenge id associated with the previously displayed code
    #[serde(rename = "challenge_id", skip_serializing_if = "Option::is_none")]
    pub challenge_id: Option<String>,
    /// The 4-digit code retrieved from Anytype Desktop app
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl ApimodelCreateApiKeyRequest {
    pub fn new() -> ApimodelCreateApiKeyRequest {
        ApimodelCreateApiKeyRequest {
            challenge_id: None,
            code: None,
        }
    }
}

