/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelPropertyWithValue {
    ApimodelTextPropertyValue(Box<models::ApimodelTextPropertyValue>),
    ApimodelNumberPropertyValue(Box<models::ApimodelNumberPropertyValue>),
    ApimodelSelectPropertyValue(Box<models::ApimodelSelectPropertyValue>),
    ApimodelMultiSelectPropertyValue(Box<models::ApimodelMultiSelectPropertyValue>),
    ApimodelDatePropertyValue(Box<models::ApimodelDatePropertyValue>),
    ApimodelFilesPropertyValue(Box<models::ApimodelFilesPropertyValue>),
    ApimodelCheckboxPropertyValue(Box<models::ApimodelCheckboxPropertyValue>),
    ApimodelUrlPropertyValue(Box<models::ApimodelUrlPropertyValue>),
    ApimodelEmailPropertyValue(Box<models::ApimodelEmailPropertyValue>),
    ApimodelPhonePropertyValue(Box<models::ApimodelPhonePropertyValue>),
    ApimodelObjectsPropertyValue(Box<models::ApimodelObjectsPropertyValue>),
}

impl Default for ApimodelPropertyWithValue {
    fn default() -> Self {
        Self::ApimodelTextPropertyValue(Default::default())
    }
}

