/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelPropertyFormat : The format of the property used for filtering
/// The format of the property used for filtering
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApimodelPropertyFormat {
    #[serde(rename = "text")]
    PropertyFormatText,
    #[serde(rename = "number")]
    PropertyFormatNumber,
    #[serde(rename = "select")]
    PropertyFormatSelect,
    #[serde(rename = "multi_select")]
    PropertyFormatMultiSelect,
    #[serde(rename = "date")]
    PropertyFormatDate,
    #[serde(rename = "files")]
    PropertyFormatFiles,
    #[serde(rename = "checkbox")]
    PropertyFormatCheckbox,
    #[serde(rename = "url")]
    PropertyFormatUrl,
    #[serde(rename = "email")]
    PropertyFormatEmail,
    #[serde(rename = "phone")]
    PropertyFormatPhone,
    #[serde(rename = "objects")]
    PropertyFormatObjects,

}

impl std::fmt::Display for ApimodelPropertyFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PropertyFormatText => write!(f, "text"),
            Self::PropertyFormatNumber => write!(f, "number"),
            Self::PropertyFormatSelect => write!(f, "select"),
            Self::PropertyFormatMultiSelect => write!(f, "multi_select"),
            Self::PropertyFormatDate => write!(f, "date"),
            Self::PropertyFormatFiles => write!(f, "files"),
            Self::PropertyFormatCheckbox => write!(f, "checkbox"),
            Self::PropertyFormatUrl => write!(f, "url"),
            Self::PropertyFormatEmail => write!(f, "email"),
            Self::PropertyFormatPhone => write!(f, "phone"),
            Self::PropertyFormatObjects => write!(f, "objects"),
        }
    }
}

impl Default for ApimodelPropertyFormat {
    fn default() -> ApimodelPropertyFormat {
        Self::PropertyFormatText
    }
}

