/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelMemberResponse {
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<models::ApimodelMember>>,
}

impl ApimodelMemberResponse {
    pub fn new() -> ApimodelMemberResponse {
        ApimodelMemberResponse {
            member: None,
        }
    }
}

