/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelPeriodIconName : The name of the icon
/// The name of the icon
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApimodelPeriodIconName {
    #[serde(rename = "accessibility")]
    IconNameAccessibility,
    #[serde(rename = "add-circle")]
    IconNameAddCircle,
    #[serde(rename = "airplane")]
    IconNameAirplane,
    #[serde(rename = "alarm")]
    IconNameAlarm,
    #[serde(rename = "albums")]
    IconNameAlbums,
    #[serde(rename = "alert-circle")]
    IconNameAlertCircle,
    #[serde(rename = "american-football")]
    IconNameAmericanFootball,
    #[serde(rename = "analytics")]
    IconNameAnalytics,
    #[serde(rename = "aperture")]
    IconNameAperture,
    #[serde(rename = "apps")]
    IconNameApps,
    #[serde(rename = "archive")]
    IconNameArchive,
    #[serde(rename = "arrow-back-circle")]
    IconNameArrowBackCircle,
    #[serde(rename = "arrow-down-circle")]
    IconNameArrowDownCircle,
    #[serde(rename = "arrow-forward-circle")]
    IconNameArrowForwardCircle,
    #[serde(rename = "arrow-redo-circle")]
    IconNameArrowRedoCircle,
    #[serde(rename = "arrow-redo")]
    IconNameArrowRedo,
    #[serde(rename = "arrow-undo-circle")]
    IconNameArrowUndoCircle,
    #[serde(rename = "arrow-undo")]
    IconNameArrowUndo,
    #[serde(rename = "arrow-up-circle")]
    IconNameArrowUpCircle,
    #[serde(rename = "at-circle")]
    IconNameAtCircle,
    #[serde(rename = "attach")]
    IconNameAttach,
    #[serde(rename = "backspace")]
    IconNameBackspace,
    #[serde(rename = "bag-add")]
    IconNameBagAdd,
    #[serde(rename = "bag-check")]
    IconNameBagCheck,
    #[serde(rename = "bag-handle")]
    IconNameBagHandle,
    #[serde(rename = "bag-remove")]
    IconNameBagRemove,
    #[serde(rename = "bag")]
    IconNameBag,
    #[serde(rename = "balloon")]
    IconNameBalloon,
    #[serde(rename = "ban")]
    IconNameBan,
    #[serde(rename = "bandage")]
    IconNameBandage,
    #[serde(rename = "bar-chart")]
    IconNameBarChart,
    #[serde(rename = "barbell")]
    IconNameBarbell,
    #[serde(rename = "barcode")]
    IconNameBarcode,
    #[serde(rename = "baseball")]
    IconNameBaseball,
    #[serde(rename = "basket")]
    IconNameBasket,
    #[serde(rename = "basketball")]
    IconNameBasketball,
    #[serde(rename = "battery-charging")]
    IconNameBatteryCharging,
    #[serde(rename = "battery-dead")]
    IconNameBatteryDead,
    #[serde(rename = "battery-full")]
    IconNameBatteryFull,
    #[serde(rename = "battery-half")]
    IconNameBatteryHalf,
    #[serde(rename = "beaker")]
    IconNameBeaker,
    #[serde(rename = "bed")]
    IconNameBed,
    #[serde(rename = "beer")]
    IconNameBeer,
    #[serde(rename = "bicycle")]
    IconNameBicycle,
    #[serde(rename = "binoculars")]
    IconNameBinoculars,
    #[serde(rename = "bluetooth")]
    IconNameBluetooth,
    #[serde(rename = "boat")]
    IconNameBoat,
    #[serde(rename = "body")]
    IconNameBody,
    #[serde(rename = "bonfire")]
    IconNameBonfire,
    #[serde(rename = "book")]
    IconNameBook,
    #[serde(rename = "bookmark")]
    IconNameBookmark,
    #[serde(rename = "bookmarks")]
    IconNameBookmarks,
    #[serde(rename = "bowling-ball")]
    IconNameBowlingBall,
    #[serde(rename = "briefcase")]
    IconNameBriefcase,
    #[serde(rename = "browsers")]
    IconNameBrowsers,
    #[serde(rename = "brush")]
    IconNameBrush,
    #[serde(rename = "bug")]
    IconNameBug,
    #[serde(rename = "build")]
    IconNameBuild,
    #[serde(rename = "bulb")]
    IconNameBulb,
    #[serde(rename = "bus")]
    IconNameBus,
    #[serde(rename = "business")]
    IconNameBusiness,
    #[serde(rename = "cafe")]
    IconNameCafe,
    #[serde(rename = "calculator")]
    IconNameCalculator,
    #[serde(rename = "calendar-clear")]
    IconNameCalendarClear,
    #[serde(rename = "calendar-number")]
    IconNameCalendarNumber,
    #[serde(rename = "calendar")]
    IconNameCalendar,
    #[serde(rename = "call")]
    IconNameCall,
    #[serde(rename = "camera-reverse")]
    IconNameCameraReverse,
    #[serde(rename = "camera")]
    IconNameCamera,
    #[serde(rename = "car-sport")]
    IconNameCarSport,
    #[serde(rename = "car")]
    IconNameCar,
    #[serde(rename = "card")]
    IconNameCard,
    #[serde(rename = "caret-back-circle")]
    IconNameCaretBackCircle,
    #[serde(rename = "caret-back")]
    IconNameCaretBack,
    #[serde(rename = "caret-down-circle")]
    IconNameCaretDownCircle,
    #[serde(rename = "caret-down")]
    IconNameCaretDown,
    #[serde(rename = "caret-forward-circle")]
    IconNameCaretForwardCircle,
    #[serde(rename = "caret-forward")]
    IconNameCaretForward,
    #[serde(rename = "caret-up-circle")]
    IconNameCaretUpCircle,
    #[serde(rename = "caret-up")]
    IconNameCaretUp,
    #[serde(rename = "cart")]
    IconNameCart,
    #[serde(rename = "cash")]
    IconNameCash,
    #[serde(rename = "cellular")]
    IconNameCellular,
    #[serde(rename = "chatbox-ellipses")]
    IconNameChatboxEllipses,
    #[serde(rename = "chatbox")]
    IconNameChatbox,
    #[serde(rename = "chatbubble-ellipses")]
    IconNameChatbubbleEllipses,
    #[serde(rename = "chatbubble")]
    IconNameChatbubble,
    #[serde(rename = "chatbubbles")]
    IconNameChatbubbles,
    #[serde(rename = "checkbox")]
    IconNameCheckbox,
    #[serde(rename = "checkmark-circle")]
    IconNameCheckmarkCircle,
    #[serde(rename = "checkmark-done-circle")]
    IconNameCheckmarkDoneCircle,
    #[serde(rename = "chevron-back-circle")]
    IconNameChevronBackCircle,
    #[serde(rename = "chevron-down-circle")]
    IconNameChevronDownCircle,
    #[serde(rename = "chevron-forward-circle")]
    IconNameChevronForwardCircle,
    #[serde(rename = "chevron-up-circle")]
    IconNameChevronUpCircle,
    #[serde(rename = "clipboard")]
    IconNameClipboard,
    #[serde(rename = "close-circle")]
    IconNameCloseCircle,
    #[serde(rename = "cloud-circle")]
    IconNameCloudCircle,
    #[serde(rename = "cloud-done")]
    IconNameCloudDone,
    #[serde(rename = "cloud-download")]
    IconNameCloudDownload,
    #[serde(rename = "cloud-offline")]
    IconNameCloudOffline,
    #[serde(rename = "cloud-upload")]
    IconNameCloudUpload,
    #[serde(rename = "cloud")]
    IconNameCloud,
    #[serde(rename = "cloudy-night")]
    IconNameCloudyNight,
    #[serde(rename = "cloudy")]
    IconNameCloudy,
    #[serde(rename = "code-slash")]
    IconNameCodeSlash,
    #[serde(rename = "code")]
    IconNameCode,
    #[serde(rename = "cog")]
    IconNameCog,
    #[serde(rename = "color-fill")]
    IconNameColorFill,
    #[serde(rename = "color-filter")]
    IconNameColorFilter,
    #[serde(rename = "color-palette")]
    IconNameColorPalette,
    #[serde(rename = "color-wand")]
    IconNameColorWand,
    #[serde(rename = "compass")]
    IconNameCompass,
    #[serde(rename = "construct")]
    IconNameConstruct,
    #[serde(rename = "contact")]
    IconNameContact,
    #[serde(rename = "contract")]
    IconNameContract,
    #[serde(rename = "contrast")]
    IconNameContrast,
    #[serde(rename = "copy")]
    IconNameCopy,
    #[serde(rename = "create")]
    IconNameCreate,
    #[serde(rename = "crop")]
    IconNameCrop,
    #[serde(rename = "cube")]
    IconNameCube,
    #[serde(rename = "cut")]
    IconNameCut,
    #[serde(rename = "desktop")]
    IconNameDesktop,
    #[serde(rename = "diamond")]
    IconNameDiamond,
    #[serde(rename = "dice")]
    IconNameDice,
    #[serde(rename = "disc")]
    IconNameDisc,
    #[serde(rename = "document-attach")]
    IconNameDocumentAttach,
    #[serde(rename = "document-lock")]
    IconNameDocumentLock,
    #[serde(rename = "document-text")]
    IconNameDocumentText,
    #[serde(rename = "document")]
    IconNameDocument,
    #[serde(rename = "documents")]
    IconNameDocuments,
    #[serde(rename = "download")]
    IconNameDownload,
    #[serde(rename = "duplicate")]
    IconNameDuplicate,
    #[serde(rename = "ear")]
    IconNameEar,
    #[serde(rename = "earth")]
    IconNameEarth,
    #[serde(rename = "easel")]
    IconNameEasel,
    #[serde(rename = "egg")]
    IconNameEgg,
    #[serde(rename = "ellipse")]
    IconNameEllipse,
    #[serde(rename = "ellipsis-horizontal-circle")]
    IconNameEllipsisHorizontalCircle,
    #[serde(rename = "ellipsis-vertical-circle")]
    IconNameEllipsisVerticalCircle,
    #[serde(rename = "enter")]
    IconNameEnter,
    #[serde(rename = "exit")]
    IconNameExit,
    #[serde(rename = "expand")]
    IconNameExpand,
    #[serde(rename = "extension-puzzle")]
    IconNameExtensionPuzzle,
    #[serde(rename = "eye-off")]
    IconNameEyeOff,
    #[serde(rename = "eye")]
    IconNameEye,
    #[serde(rename = "eyedrop")]
    IconNameEyedrop,
    #[serde(rename = "fast-food")]
    IconNameFastFood,
    #[serde(rename = "female")]
    IconNameFemale,
    #[serde(rename = "file-tray-full")]
    IconNameFileTrayFull,
    #[serde(rename = "file-tray-stacked")]
    IconNameFileTrayStacked,
    #[serde(rename = "file-tray")]
    IconNameFileTray,
    #[serde(rename = "film")]
    IconNameFilm,
    #[serde(rename = "filter-circle")]
    IconNameFilterCircle,
    #[serde(rename = "finger-print")]
    IconNameFingerPrint,
    #[serde(rename = "fish")]
    IconNameFish,
    #[serde(rename = "fitness")]
    IconNameFitness,
    #[serde(rename = "flag")]
    IconNameFlag,
    #[serde(rename = "flame")]
    IconNameFlame,
    #[serde(rename = "flash-off")]
    IconNameFlashOff,
    #[serde(rename = "flash")]
    IconNameFlash,
    #[serde(rename = "flashlight")]
    IconNameFlashlight,
    #[serde(rename = "flask")]
    IconNameFlask,
    #[serde(rename = "flower")]
    IconNameFlower,
    #[serde(rename = "folder-open")]
    IconNameFolderOpen,
    #[serde(rename = "folder")]
    IconNameFolder,
    #[serde(rename = "football")]
    IconNameFootball,
    #[serde(rename = "footsteps")]
    IconNameFootsteps,
    #[serde(rename = "funnel")]
    IconNameFunnel,
    #[serde(rename = "game-controller")]
    IconNameGameController,
    #[serde(rename = "gift")]
    IconNameGift,
    #[serde(rename = "git-branch")]
    IconNameGitBranch,
    #[serde(rename = "git-commit")]
    IconNameGitCommit,
    #[serde(rename = "git-compare")]
    IconNameGitCompare,
    #[serde(rename = "git-merge")]
    IconNameGitMerge,
    #[serde(rename = "git-network")]
    IconNameGitNetwork,
    #[serde(rename = "git-pull-request")]
    IconNameGitPullRequest,
    #[serde(rename = "glasses")]
    IconNameGlasses,
    #[serde(rename = "globe")]
    IconNameGlobe,
    #[serde(rename = "golf")]
    IconNameGolf,
    #[serde(rename = "grid")]
    IconNameGrid,
    #[serde(rename = "hammer")]
    IconNameHammer,
    #[serde(rename = "hand-left")]
    IconNameHandLeft,
    #[serde(rename = "hand-right")]
    IconNameHandRight,
    #[serde(rename = "happy")]
    IconNameHappy,
    #[serde(rename = "hardware-chip")]
    IconNameHardwareChip,
    #[serde(rename = "headset")]
    IconNameHeadset,
    #[serde(rename = "heart-circle")]
    IconNameHeartCircle,
    #[serde(rename = "heart-dislike-circle")]
    IconNameHeartDislikeCircle,
    #[serde(rename = "heart-dislike")]
    IconNameHeartDislike,
    #[serde(rename = "heart-half")]
    IconNameHeartHalf,
    #[serde(rename = "heart")]
    IconNameHeart,
    #[serde(rename = "help-buoy")]
    IconNameHelpBuoy,
    #[serde(rename = "help-circle")]
    IconNameHelpCircle,
    #[serde(rename = "home")]
    IconNameHome,
    #[serde(rename = "hourglass")]
    IconNameHourglass,
    #[serde(rename = "ice-cream")]
    IconNameIceCream,
    #[serde(rename = "id-card")]
    IconNameIdCard,
    #[serde(rename = "image")]
    IconNameImage,
    #[serde(rename = "images")]
    IconNameImages,
    #[serde(rename = "infinite")]
    IconNameInfinite,
    #[serde(rename = "information-circle")]
    IconNameInformationCircle,
    #[serde(rename = "invert-mode")]
    IconNameInvertMode,
    #[serde(rename = "journal")]
    IconNameJournal,
    #[serde(rename = "key")]
    IconNameKey,
    #[serde(rename = "keypad")]
    IconNameKeypad,
    #[serde(rename = "language")]
    IconNameLanguage,
    #[serde(rename = "laptop")]
    IconNameLaptop,
    #[serde(rename = "layers")]
    IconNameLayers,
    #[serde(rename = "leaf")]
    IconNameLeaf,
    #[serde(rename = "library")]
    IconNameLibrary,
    #[serde(rename = "link")]
    IconNameLink,
    #[serde(rename = "list-circle")]
    IconNameListCircle,
    #[serde(rename = "list")]
    IconNameList,
    #[serde(rename = "locate")]
    IconNameLocate,
    #[serde(rename = "location")]
    IconNameLocation,
    #[serde(rename = "lock-closed")]
    IconNameLockClosed,
    #[serde(rename = "lock-open")]
    IconNameLockOpen,
    #[serde(rename = "log-in")]
    IconNameLogIn,
    #[serde(rename = "log-out")]
    IconNameLogOut,
    #[serde(rename = "logo-alipay")]
    IconNameLogoAlipay,
    #[serde(rename = "logo-amazon")]
    IconNameLogoAmazon,
    #[serde(rename = "logo-amplify")]
    IconNameLogoAmplify,
    #[serde(rename = "logo-android")]
    IconNameLogoAndroid,
    #[serde(rename = "magnet")]
    IconNameMagnet,
    #[serde(rename = "mail-open")]
    IconNameMailOpen,
    #[serde(rename = "mail-unread")]
    IconNameMailUnread,
    #[serde(rename = "mail")]
    IconNameMail,
    #[serde(rename = "male-female")]
    IconNameMaleFemale,
    #[serde(rename = "male")]
    IconNameMale,
    #[serde(rename = "man")]
    IconNameMan,
    #[serde(rename = "map")]
    IconNameMap,
    #[serde(rename = "medal")]
    IconNameMedal,
    #[serde(rename = "medical")]
    IconNameMedical,
    #[serde(rename = "medkit")]
    IconNameMedkit,
    #[serde(rename = "megaphone")]
    IconNameMegaphone,
    #[serde(rename = "menu")]
    IconNameMenu,
    #[serde(rename = "mic-circle")]
    IconNameMicCircle,
    #[serde(rename = "mic-off-circle")]
    IconNameMicOffCircle,
    #[serde(rename = "mic-off")]
    IconNameMicOff,
    #[serde(rename = "mic")]
    IconNameMic,
    #[serde(rename = "moon")]
    IconNameMoon,
    #[serde(rename = "move")]
    IconNameMove,
    #[serde(rename = "musical-note")]
    IconNameMusicalNote,
    #[serde(rename = "musical-notes")]
    IconNameMusicalNotes,
    #[serde(rename = "navigate-circle")]
    IconNameNavigateCircle,
    #[serde(rename = "navigate")]
    IconNameNavigate,
    #[serde(rename = "newspaper")]
    IconNameNewspaper,
    #[serde(rename = "notifications-circle")]
    IconNameNotificationsCircle,
    #[serde(rename = "notifications-off-circle")]
    IconNameNotificationsOffCircle,
    #[serde(rename = "notifications-off")]
    IconNameNotificationsOff,
    #[serde(rename = "notifications")]
    IconNameNotifications,
    #[serde(rename = "nuclear")]
    IconNameNuclear,
    #[serde(rename = "nutrition")]
    IconNameNutrition,
    #[serde(rename = "options")]
    IconNameOptions,
    #[serde(rename = "paper-plane")]
    IconNamePaperPlane,
    #[serde(rename = "partly-sunny")]
    IconNamePartlySunny,
    #[serde(rename = "pause-circle")]
    IconNamePauseCircle,
    #[serde(rename = "pause")]
    IconNamePause,
    #[serde(rename = "paw")]
    IconNamePaw,
    #[serde(rename = "pencil")]
    IconNamePencil,
    #[serde(rename = "people-circle")]
    IconNamePeopleCircle,
    #[serde(rename = "people")]
    IconNamePeople,
    #[serde(rename = "person-add")]
    IconNamePersonAdd,
    #[serde(rename = "person-circle")]
    IconNamePersonCircle,
    #[serde(rename = "person-remove")]
    IconNamePersonRemove,
    #[serde(rename = "person")]
    IconNamePerson,
    #[serde(rename = "phone-landscape")]
    IconNamePhoneLandscape,
    #[serde(rename = "phone-portrait")]
    IconNamePhonePortrait,
    #[serde(rename = "pie-chart")]
    IconNamePieChart,
    #[serde(rename = "pin")]
    IconNamePin,
    #[serde(rename = "pint")]
    IconNamePint,
    #[serde(rename = "pizza")]
    IconNamePizza,
    #[serde(rename = "planet")]
    IconNamePlanet,
    #[serde(rename = "play-back-circle")]
    IconNamePlayBackCircle,
    #[serde(rename = "play-back")]
    IconNamePlayBack,
    #[serde(rename = "play-circle")]
    IconNamePlayCircle,
    #[serde(rename = "play-forward-circle")]
    IconNamePlayForwardCircle,
    #[serde(rename = "play-forward")]
    IconNamePlayForward,
    #[serde(rename = "play-skip-back-circle")]
    IconNamePlaySkipBackCircle,
    #[serde(rename = "play-skip-back")]
    IconNamePlaySkipBack,
    #[serde(rename = "play-skip-forward-circle")]
    IconNamePlaySkipForwardCircle,
    #[serde(rename = "play-skip-forward")]
    IconNamePlaySkipForward,
    #[serde(rename = "play")]
    IconNamePlay,
    #[serde(rename = "podium")]
    IconNamePodium,
    #[serde(rename = "power")]
    IconNamePower,
    #[serde(rename = "pricetag")]
    IconNamePricetag,
    #[serde(rename = "pricetags")]
    IconNamePricetags,
    #[serde(rename = "print")]
    IconNamePrint,
    #[serde(rename = "prism")]
    IconNamePrism,
    #[serde(rename = "pulse")]
    IconNamePulse,
    #[serde(rename = "push")]
    IconNamePush,
    #[serde(rename = "qr-code")]
    IconNameQrCode,
    #[serde(rename = "radio-button-off")]
    IconNameRadioButtonOff,
    #[serde(rename = "radio-button-on")]
    IconNameRadioButtonOn,
    #[serde(rename = "radio")]
    IconNameRadio,
    #[serde(rename = "rainy")]
    IconNameRainy,
    #[serde(rename = "reader")]
    IconNameReader,
    #[serde(rename = "receipt")]
    IconNameReceipt,
    #[serde(rename = "recording")]
    IconNameRecording,
    #[serde(rename = "refresh-circle")]
    IconNameRefreshCircle,
    #[serde(rename = "refresh")]
    IconNameRefresh,
    #[serde(rename = "reload-circle")]
    IconNameReloadCircle,
    #[serde(rename = "reload")]
    IconNameReload,
    #[serde(rename = "remove-circle")]
    IconNameRemoveCircle,
    #[serde(rename = "repeat")]
    IconNameRepeat,
    #[serde(rename = "resize")]
    IconNameResize,
    #[serde(rename = "restaurant")]
    IconNameRestaurant,
    #[serde(rename = "ribbon")]
    IconNameRibbon,
    #[serde(rename = "rocket")]
    IconNameRocket,
    #[serde(rename = "rose")]
    IconNameRose,
    #[serde(rename = "sad")]
    IconNameSad,
    #[serde(rename = "save")]
    IconNameSave,
    #[serde(rename = "scale")]
    IconNameScale,
    #[serde(rename = "scan-circle")]
    IconNameScanCircle,
    #[serde(rename = "scan")]
    IconNameScan,
    #[serde(rename = "school")]
    IconNameSchool,
    #[serde(rename = "search-circle")]
    IconNameSearchCircle,
    #[serde(rename = "search")]
    IconNameSearch,
    #[serde(rename = "send")]
    IconNameSend,
    #[serde(rename = "server")]
    IconNameServer,
    #[serde(rename = "settings")]
    IconNameSettings,
    #[serde(rename = "shapes")]
    IconNameShapes,
    #[serde(rename = "share-social")]
    IconNameShareSocial,
    #[serde(rename = "share")]
    IconNameShare,
    #[serde(rename = "shield-checkmark")]
    IconNameShieldCheckmark,
    #[serde(rename = "shield-half")]
    IconNameShieldHalf,
    #[serde(rename = "shield")]
    IconNameShield,
    #[serde(rename = "shirt")]
    IconNameShirt,
    #[serde(rename = "shuffle")]
    IconNameShuffle,
    #[serde(rename = "skull")]
    IconNameSkull,
    #[serde(rename = "snow")]
    IconNameSnow,
    #[serde(rename = "sparkles")]
    IconNameSparkles,
    #[serde(rename = "speedometer")]
    IconNameSpeedometer,
    #[serde(rename = "square")]
    IconNameSquare,
    #[serde(rename = "star-half")]
    IconNameStarHalf,
    #[serde(rename = "star")]
    IconNameStar,
    #[serde(rename = "stats-chart")]
    IconNameStatsChart,
    #[serde(rename = "stop-circle")]
    IconNameStopCircle,
    #[serde(rename = "stop")]
    IconNameStop,
    #[serde(rename = "stopwatch")]
    IconNameStopwatch,
    #[serde(rename = "storefront")]
    IconNameStorefront,
    #[serde(rename = "subway")]
    IconNameSubway,
    #[serde(rename = "sunny")]
    IconNameSunny,
    #[serde(rename = "swap-horizontal")]
    IconNameSwapHorizontal,
    #[serde(rename = "swap-vertical")]
    IconNameSwapVertical,
    #[serde(rename = "sync-circle")]
    IconNameSyncCircle,
    #[serde(rename = "sync")]
    IconNameSync,
    #[serde(rename = "t.txt")]
    IconNameTabletLandscape,
    #[serde(rename = "tablet-landscape")]
    IconNameTabletPortrait,
    #[serde(rename = "tablet-portrait")]
    IconNameTelescope,
    #[serde(rename = "telescope")]
    IconNameTennisball,
    #[serde(rename = "tennisball")]
    IconNameTerminal,
    #[serde(rename = "terminal")]
    IconNameText,
    #[serde(rename = "text")]
    IconNameThermometer,
    #[serde(rename = "thermometer")]
    IconNameThumbsDown,
    #[serde(rename = "thumbs-down")]
    IconNameThumbsUp,
    #[serde(rename = "thumbs-up")]
    IconNameThunderstorm,
    #[serde(rename = "thunderstorm")]
    IconNameTicket,
    #[serde(rename = "ticket")]
    IconNameTime,
    #[serde(rename = "time")]
    IconNameTimer,
    #[serde(rename = "timer")]
    IconNameToday,
    #[serde(rename = "today")]
    IconNameToggle,
    #[serde(rename = "toggle")]
    IconNameTrailSign,
    #[serde(rename = "trail-sign")]
    IconNameTrain,
    #[serde(rename = "train")]
    IconNameTransgender,
    #[serde(rename = "transgender")]
    IconNameTrashBin,
    #[serde(rename = "trash-bin")]
    IconNameTrash,
    #[serde(rename = "trash")]
    IconNameTrendingDown,
    #[serde(rename = "trending-down")]
    IconNameTrendingUp,
    #[serde(rename = "trending-up")]
    IconNameTriangle,
    #[serde(rename = "triangle")]
    IconNameTrophy,
    #[serde(rename = "trophy")]
    IconNameTv,
    #[serde(rename = "tv")]
    IconNameUmbrella,
    #[serde(rename = "umbrella")]
    IconNameUnlink,
    #[serde(rename = "unlink")]
    IconNameVideocamOff,
    #[serde(rename = "videocam-off")]
    IconNameVideocam,
    #[serde(rename = "videocam")]
    IconNameVolumeHigh,
    #[serde(rename = "volume-high")]
    IconNameVolumeLow,
    #[serde(rename = "volume-low")]
    IconNameVolumeMedium,
    #[serde(rename = "volume-medium")]
    IconNameVolumeMute,
    #[serde(rename = "volume-mute")]
    IconNameVolumeOff,
    #[serde(rename = "volume-off")]
    IconNameWalk,
    #[serde(rename = "walk")]
    IconNameWallet,
    #[serde(rename = "wallet")]
    IconNameWarning,
    #[serde(rename = "warning")]
    IconNameWatch,
    #[serde(rename = "watch")]
    IconNameWater,
    #[serde(rename = "water")]
    IconNameWifi,
    #[serde(rename = "wifi")]
    IconNameWine,
    #[serde(rename = "wine")]
    IconNameWoman,
    #[serde(rename = "woman")]
    Woman,

}

impl std::fmt::Display for ApimodelPeriodIconName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::IconNameAccessibility => write!(f, "accessibility"),
            Self::IconNameAddCircle => write!(f, "add-circle"),
            Self::IconNameAirplane => write!(f, "airplane"),
            Self::IconNameAlarm => write!(f, "alarm"),
            Self::IconNameAlbums => write!(f, "albums"),
            Self::IconNameAlertCircle => write!(f, "alert-circle"),
            Self::IconNameAmericanFootball => write!(f, "american-football"),
            Self::IconNameAnalytics => write!(f, "analytics"),
            Self::IconNameAperture => write!(f, "aperture"),
            Self::IconNameApps => write!(f, "apps"),
            Self::IconNameArchive => write!(f, "archive"),
            Self::IconNameArrowBackCircle => write!(f, "arrow-back-circle"),
            Self::IconNameArrowDownCircle => write!(f, "arrow-down-circle"),
            Self::IconNameArrowForwardCircle => write!(f, "arrow-forward-circle"),
            Self::IconNameArrowRedoCircle => write!(f, "arrow-redo-circle"),
            Self::IconNameArrowRedo => write!(f, "arrow-redo"),
            Self::IconNameArrowUndoCircle => write!(f, "arrow-undo-circle"),
            Self::IconNameArrowUndo => write!(f, "arrow-undo"),
            Self::IconNameArrowUpCircle => write!(f, "arrow-up-circle"),
            Self::IconNameAtCircle => write!(f, "at-circle"),
            Self::IconNameAttach => write!(f, "attach"),
            Self::IconNameBackspace => write!(f, "backspace"),
            Self::IconNameBagAdd => write!(f, "bag-add"),
            Self::IconNameBagCheck => write!(f, "bag-check"),
            Self::IconNameBagHandle => write!(f, "bag-handle"),
            Self::IconNameBagRemove => write!(f, "bag-remove"),
            Self::IconNameBag => write!(f, "bag"),
            Self::IconNameBalloon => write!(f, "balloon"),
            Self::IconNameBan => write!(f, "ban"),
            Self::IconNameBandage => write!(f, "bandage"),
            Self::IconNameBarChart => write!(f, "bar-chart"),
            Self::IconNameBarbell => write!(f, "barbell"),
            Self::IconNameBarcode => write!(f, "barcode"),
            Self::IconNameBaseball => write!(f, "baseball"),
            Self::IconNameBasket => write!(f, "basket"),
            Self::IconNameBasketball => write!(f, "basketball"),
            Self::IconNameBatteryCharging => write!(f, "battery-charging"),
            Self::IconNameBatteryDead => write!(f, "battery-dead"),
            Self::IconNameBatteryFull => write!(f, "battery-full"),
            Self::IconNameBatteryHalf => write!(f, "battery-half"),
            Self::IconNameBeaker => write!(f, "beaker"),
            Self::IconNameBed => write!(f, "bed"),
            Self::IconNameBeer => write!(f, "beer"),
            Self::IconNameBicycle => write!(f, "bicycle"),
            Self::IconNameBinoculars => write!(f, "binoculars"),
            Self::IconNameBluetooth => write!(f, "bluetooth"),
            Self::IconNameBoat => write!(f, "boat"),
            Self::IconNameBody => write!(f, "body"),
            Self::IconNameBonfire => write!(f, "bonfire"),
            Self::IconNameBook => write!(f, "book"),
            Self::IconNameBookmark => write!(f, "bookmark"),
            Self::IconNameBookmarks => write!(f, "bookmarks"),
            Self::IconNameBowlingBall => write!(f, "bowling-ball"),
            Self::IconNameBriefcase => write!(f, "briefcase"),
            Self::IconNameBrowsers => write!(f, "browsers"),
            Self::IconNameBrush => write!(f, "brush"),
            Self::IconNameBug => write!(f, "bug"),
            Self::IconNameBuild => write!(f, "build"),
            Self::IconNameBulb => write!(f, "bulb"),
            Self::IconNameBus => write!(f, "bus"),
            Self::IconNameBusiness => write!(f, "business"),
            Self::IconNameCafe => write!(f, "cafe"),
            Self::IconNameCalculator => write!(f, "calculator"),
            Self::IconNameCalendarClear => write!(f, "calendar-clear"),
            Self::IconNameCalendarNumber => write!(f, "calendar-number"),
            Self::IconNameCalendar => write!(f, "calendar"),
            Self::IconNameCall => write!(f, "call"),
            Self::IconNameCameraReverse => write!(f, "camera-reverse"),
            Self::IconNameCamera => write!(f, "camera"),
            Self::IconNameCarSport => write!(f, "car-sport"),
            Self::IconNameCar => write!(f, "car"),
            Self::IconNameCard => write!(f, "card"),
            Self::IconNameCaretBackCircle => write!(f, "caret-back-circle"),
            Self::IconNameCaretBack => write!(f, "caret-back"),
            Self::IconNameCaretDownCircle => write!(f, "caret-down-circle"),
            Self::IconNameCaretDown => write!(f, "caret-down"),
            Self::IconNameCaretForwardCircle => write!(f, "caret-forward-circle"),
            Self::IconNameCaretForward => write!(f, "caret-forward"),
            Self::IconNameCaretUpCircle => write!(f, "caret-up-circle"),
            Self::IconNameCaretUp => write!(f, "caret-up"),
            Self::IconNameCart => write!(f, "cart"),
            Self::IconNameCash => write!(f, "cash"),
            Self::IconNameCellular => write!(f, "cellular"),
            Self::IconNameChatboxEllipses => write!(f, "chatbox-ellipses"),
            Self::IconNameChatbox => write!(f, "chatbox"),
            Self::IconNameChatbubbleEllipses => write!(f, "chatbubble-ellipses"),
            Self::IconNameChatbubble => write!(f, "chatbubble"),
            Self::IconNameChatbubbles => write!(f, "chatbubbles"),
            Self::IconNameCheckbox => write!(f, "checkbox"),
            Self::IconNameCheckmarkCircle => write!(f, "checkmark-circle"),
            Self::IconNameCheckmarkDoneCircle => write!(f, "checkmark-done-circle"),
            Self::IconNameChevronBackCircle => write!(f, "chevron-back-circle"),
            Self::IconNameChevronDownCircle => write!(f, "chevron-down-circle"),
            Self::IconNameChevronForwardCircle => write!(f, "chevron-forward-circle"),
            Self::IconNameChevronUpCircle => write!(f, "chevron-up-circle"),
            Self::IconNameClipboard => write!(f, "clipboard"),
            Self::IconNameCloseCircle => write!(f, "close-circle"),
            Self::IconNameCloudCircle => write!(f, "cloud-circle"),
            Self::IconNameCloudDone => write!(f, "cloud-done"),
            Self::IconNameCloudDownload => write!(f, "cloud-download"),
            Self::IconNameCloudOffline => write!(f, "cloud-offline"),
            Self::IconNameCloudUpload => write!(f, "cloud-upload"),
            Self::IconNameCloud => write!(f, "cloud"),
            Self::IconNameCloudyNight => write!(f, "cloudy-night"),
            Self::IconNameCloudy => write!(f, "cloudy"),
            Self::IconNameCodeSlash => write!(f, "code-slash"),
            Self::IconNameCode => write!(f, "code"),
            Self::IconNameCog => write!(f, "cog"),
            Self::IconNameColorFill => write!(f, "color-fill"),
            Self::IconNameColorFilter => write!(f, "color-filter"),
            Self::IconNameColorPalette => write!(f, "color-palette"),
            Self::IconNameColorWand => write!(f, "color-wand"),
            Self::IconNameCompass => write!(f, "compass"),
            Self::IconNameConstruct => write!(f, "construct"),
            Self::IconNameContact => write!(f, "contact"),
            Self::IconNameContract => write!(f, "contract"),
            Self::IconNameContrast => write!(f, "contrast"),
            Self::IconNameCopy => write!(f, "copy"),
            Self::IconNameCreate => write!(f, "create"),
            Self::IconNameCrop => write!(f, "crop"),
            Self::IconNameCube => write!(f, "cube"),
            Self::IconNameCut => write!(f, "cut"),
            Self::IconNameDesktop => write!(f, "desktop"),
            Self::IconNameDiamond => write!(f, "diamond"),
            Self::IconNameDice => write!(f, "dice"),
            Self::IconNameDisc => write!(f, "disc"),
            Self::IconNameDocumentAttach => write!(f, "document-attach"),
            Self::IconNameDocumentLock => write!(f, "document-lock"),
            Self::IconNameDocumentText => write!(f, "document-text"),
            Self::IconNameDocument => write!(f, "document"),
            Self::IconNameDocuments => write!(f, "documents"),
            Self::IconNameDownload => write!(f, "download"),
            Self::IconNameDuplicate => write!(f, "duplicate"),
            Self::IconNameEar => write!(f, "ear"),
            Self::IconNameEarth => write!(f, "earth"),
            Self::IconNameEasel => write!(f, "easel"),
            Self::IconNameEgg => write!(f, "egg"),
            Self::IconNameEllipse => write!(f, "ellipse"),
            Self::IconNameEllipsisHorizontalCircle => write!(f, "ellipsis-horizontal-circle"),
            Self::IconNameEllipsisVerticalCircle => write!(f, "ellipsis-vertical-circle"),
            Self::IconNameEnter => write!(f, "enter"),
            Self::IconNameExit => write!(f, "exit"),
            Self::IconNameExpand => write!(f, "expand"),
            Self::IconNameExtensionPuzzle => write!(f, "extension-puzzle"),
            Self::IconNameEyeOff => write!(f, "eye-off"),
            Self::IconNameEye => write!(f, "eye"),
            Self::IconNameEyedrop => write!(f, "eyedrop"),
            Self::IconNameFastFood => write!(f, "fast-food"),
            Self::IconNameFemale => write!(f, "female"),
            Self::IconNameFileTrayFull => write!(f, "file-tray-full"),
            Self::IconNameFileTrayStacked => write!(f, "file-tray-stacked"),
            Self::IconNameFileTray => write!(f, "file-tray"),
            Self::IconNameFilm => write!(f, "film"),
            Self::IconNameFilterCircle => write!(f, "filter-circle"),
            Self::IconNameFingerPrint => write!(f, "finger-print"),
            Self::IconNameFish => write!(f, "fish"),
            Self::IconNameFitness => write!(f, "fitness"),
            Self::IconNameFlag => write!(f, "flag"),
            Self::IconNameFlame => write!(f, "flame"),
            Self::IconNameFlashOff => write!(f, "flash-off"),
            Self::IconNameFlash => write!(f, "flash"),
            Self::IconNameFlashlight => write!(f, "flashlight"),
            Self::IconNameFlask => write!(f, "flask"),
            Self::IconNameFlower => write!(f, "flower"),
            Self::IconNameFolderOpen => write!(f, "folder-open"),
            Self::IconNameFolder => write!(f, "folder"),
            Self::IconNameFootball => write!(f, "football"),
            Self::IconNameFootsteps => write!(f, "footsteps"),
            Self::IconNameFunnel => write!(f, "funnel"),
            Self::IconNameGameController => write!(f, "game-controller"),
            Self::IconNameGift => write!(f, "gift"),
            Self::IconNameGitBranch => write!(f, "git-branch"),
            Self::IconNameGitCommit => write!(f, "git-commit"),
            Self::IconNameGitCompare => write!(f, "git-compare"),
            Self::IconNameGitMerge => write!(f, "git-merge"),
            Self::IconNameGitNetwork => write!(f, "git-network"),
            Self::IconNameGitPullRequest => write!(f, "git-pull-request"),
            Self::IconNameGlasses => write!(f, "glasses"),
            Self::IconNameGlobe => write!(f, "globe"),
            Self::IconNameGolf => write!(f, "golf"),
            Self::IconNameGrid => write!(f, "grid"),
            Self::IconNameHammer => write!(f, "hammer"),
            Self::IconNameHandLeft => write!(f, "hand-left"),
            Self::IconNameHandRight => write!(f, "hand-right"),
            Self::IconNameHappy => write!(f, "happy"),
            Self::IconNameHardwareChip => write!(f, "hardware-chip"),
            Self::IconNameHeadset => write!(f, "headset"),
            Self::IconNameHeartCircle => write!(f, "heart-circle"),
            Self::IconNameHeartDislikeCircle => write!(f, "heart-dislike-circle"),
            Self::IconNameHeartDislike => write!(f, "heart-dislike"),
            Self::IconNameHeartHalf => write!(f, "heart-half"),
            Self::IconNameHeart => write!(f, "heart"),
            Self::IconNameHelpBuoy => write!(f, "help-buoy"),
            Self::IconNameHelpCircle => write!(f, "help-circle"),
            Self::IconNameHome => write!(f, "home"),
            Self::IconNameHourglass => write!(f, "hourglass"),
            Self::IconNameIceCream => write!(f, "ice-cream"),
            Self::IconNameIdCard => write!(f, "id-card"),
            Self::IconNameImage => write!(f, "image"),
            Self::IconNameImages => write!(f, "images"),
            Self::IconNameInfinite => write!(f, "infinite"),
            Self::IconNameInformationCircle => write!(f, "information-circle"),
            Self::IconNameInvertMode => write!(f, "invert-mode"),
            Self::IconNameJournal => write!(f, "journal"),
            Self::IconNameKey => write!(f, "key"),
            Self::IconNameKeypad => write!(f, "keypad"),
            Self::IconNameLanguage => write!(f, "language"),
            Self::IconNameLaptop => write!(f, "laptop"),
            Self::IconNameLayers => write!(f, "layers"),
            Self::IconNameLeaf => write!(f, "leaf"),
            Self::IconNameLibrary => write!(f, "library"),
            Self::IconNameLink => write!(f, "link"),
            Self::IconNameListCircle => write!(f, "list-circle"),
            Self::IconNameList => write!(f, "list"),
            Self::IconNameLocate => write!(f, "locate"),
            Self::IconNameLocation => write!(f, "location"),
            Self::IconNameLockClosed => write!(f, "lock-closed"),
            Self::IconNameLockOpen => write!(f, "lock-open"),
            Self::IconNameLogIn => write!(f, "log-in"),
            Self::IconNameLogOut => write!(f, "log-out"),
            Self::IconNameLogoAlipay => write!(f, "logo-alipay"),
            Self::IconNameLogoAmazon => write!(f, "logo-amazon"),
            Self::IconNameLogoAmplify => write!(f, "logo-amplify"),
            Self::IconNameLogoAndroid => write!(f, "logo-android"),
            Self::IconNameMagnet => write!(f, "magnet"),
            Self::IconNameMailOpen => write!(f, "mail-open"),
            Self::IconNameMailUnread => write!(f, "mail-unread"),
            Self::IconNameMail => write!(f, "mail"),
            Self::IconNameMaleFemale => write!(f, "male-female"),
            Self::IconNameMale => write!(f, "male"),
            Self::IconNameMan => write!(f, "man"),
            Self::IconNameMap => write!(f, "map"),
            Self::IconNameMedal => write!(f, "medal"),
            Self::IconNameMedical => write!(f, "medical"),
            Self::IconNameMedkit => write!(f, "medkit"),
            Self::IconNameMegaphone => write!(f, "megaphone"),
            Self::IconNameMenu => write!(f, "menu"),
            Self::IconNameMicCircle => write!(f, "mic-circle"),
            Self::IconNameMicOffCircle => write!(f, "mic-off-circle"),
            Self::IconNameMicOff => write!(f, "mic-off"),
            Self::IconNameMic => write!(f, "mic"),
            Self::IconNameMoon => write!(f, "moon"),
            Self::IconNameMove => write!(f, "move"),
            Self::IconNameMusicalNote => write!(f, "musical-note"),
            Self::IconNameMusicalNotes => write!(f, "musical-notes"),
            Self::IconNameNavigateCircle => write!(f, "navigate-circle"),
            Self::IconNameNavigate => write!(f, "navigate"),
            Self::IconNameNewspaper => write!(f, "newspaper"),
            Self::IconNameNotificationsCircle => write!(f, "notifications-circle"),
            Self::IconNameNotificationsOffCircle => write!(f, "notifications-off-circle"),
            Self::IconNameNotificationsOff => write!(f, "notifications-off"),
            Self::IconNameNotifications => write!(f, "notifications"),
            Self::IconNameNuclear => write!(f, "nuclear"),
            Self::IconNameNutrition => write!(f, "nutrition"),
            Self::IconNameOptions => write!(f, "options"),
            Self::IconNamePaperPlane => write!(f, "paper-plane"),
            Self::IconNamePartlySunny => write!(f, "partly-sunny"),
            Self::IconNamePauseCircle => write!(f, "pause-circle"),
            Self::IconNamePause => write!(f, "pause"),
            Self::IconNamePaw => write!(f, "paw"),
            Self::IconNamePencil => write!(f, "pencil"),
            Self::IconNamePeopleCircle => write!(f, "people-circle"),
            Self::IconNamePeople => write!(f, "people"),
            Self::IconNamePersonAdd => write!(f, "person-add"),
            Self::IconNamePersonCircle => write!(f, "person-circle"),
            Self::IconNamePersonRemove => write!(f, "person-remove"),
            Self::IconNamePerson => write!(f, "person"),
            Self::IconNamePhoneLandscape => write!(f, "phone-landscape"),
            Self::IconNamePhonePortrait => write!(f, "phone-portrait"),
            Self::IconNamePieChart => write!(f, "pie-chart"),
            Self::IconNamePin => write!(f, "pin"),
            Self::IconNamePint => write!(f, "pint"),
            Self::IconNamePizza => write!(f, "pizza"),
            Self::IconNamePlanet => write!(f, "planet"),
            Self::IconNamePlayBackCircle => write!(f, "play-back-circle"),
            Self::IconNamePlayBack => write!(f, "play-back"),
            Self::IconNamePlayCircle => write!(f, "play-circle"),
            Self::IconNamePlayForwardCircle => write!(f, "play-forward-circle"),
            Self::IconNamePlayForward => write!(f, "play-forward"),
            Self::IconNamePlaySkipBackCircle => write!(f, "play-skip-back-circle"),
            Self::IconNamePlaySkipBack => write!(f, "play-skip-back"),
            Self::IconNamePlaySkipForwardCircle => write!(f, "play-skip-forward-circle"),
            Self::IconNamePlaySkipForward => write!(f, "play-skip-forward"),
            Self::IconNamePlay => write!(f, "play"),
            Self::IconNamePodium => write!(f, "podium"),
            Self::IconNamePower => write!(f, "power"),
            Self::IconNamePricetag => write!(f, "pricetag"),
            Self::IconNamePricetags => write!(f, "pricetags"),
            Self::IconNamePrint => write!(f, "print"),
            Self::IconNamePrism => write!(f, "prism"),
            Self::IconNamePulse => write!(f, "pulse"),
            Self::IconNamePush => write!(f, "push"),
            Self::IconNameQrCode => write!(f, "qr-code"),
            Self::IconNameRadioButtonOff => write!(f, "radio-button-off"),
            Self::IconNameRadioButtonOn => write!(f, "radio-button-on"),
            Self::IconNameRadio => write!(f, "radio"),
            Self::IconNameRainy => write!(f, "rainy"),
            Self::IconNameReader => write!(f, "reader"),
            Self::IconNameReceipt => write!(f, "receipt"),
            Self::IconNameRecording => write!(f, "recording"),
            Self::IconNameRefreshCircle => write!(f, "refresh-circle"),
            Self::IconNameRefresh => write!(f, "refresh"),
            Self::IconNameReloadCircle => write!(f, "reload-circle"),
            Self::IconNameReload => write!(f, "reload"),
            Self::IconNameRemoveCircle => write!(f, "remove-circle"),
            Self::IconNameRepeat => write!(f, "repeat"),
            Self::IconNameResize => write!(f, "resize"),
            Self::IconNameRestaurant => write!(f, "restaurant"),
            Self::IconNameRibbon => write!(f, "ribbon"),
            Self::IconNameRocket => write!(f, "rocket"),
            Self::IconNameRose => write!(f, "rose"),
            Self::IconNameSad => write!(f, "sad"),
            Self::IconNameSave => write!(f, "save"),
            Self::IconNameScale => write!(f, "scale"),
            Self::IconNameScanCircle => write!(f, "scan-circle"),
            Self::IconNameScan => write!(f, "scan"),
            Self::IconNameSchool => write!(f, "school"),
            Self::IconNameSearchCircle => write!(f, "search-circle"),
            Self::IconNameSearch => write!(f, "search"),
            Self::IconNameSend => write!(f, "send"),
            Self::IconNameServer => write!(f, "server"),
            Self::IconNameSettings => write!(f, "settings"),
            Self::IconNameShapes => write!(f, "shapes"),
            Self::IconNameShareSocial => write!(f, "share-social"),
            Self::IconNameShare => write!(f, "share"),
            Self::IconNameShieldCheckmark => write!(f, "shield-checkmark"),
            Self::IconNameShieldHalf => write!(f, "shield-half"),
            Self::IconNameShield => write!(f, "shield"),
            Self::IconNameShirt => write!(f, "shirt"),
            Self::IconNameShuffle => write!(f, "shuffle"),
            Self::IconNameSkull => write!(f, "skull"),
            Self::IconNameSnow => write!(f, "snow"),
            Self::IconNameSparkles => write!(f, "sparkles"),
            Self::IconNameSpeedometer => write!(f, "speedometer"),
            Self::IconNameSquare => write!(f, "square"),
            Self::IconNameStarHalf => write!(f, "star-half"),
            Self::IconNameStar => write!(f, "star"),
            Self::IconNameStatsChart => write!(f, "stats-chart"),
            Self::IconNameStopCircle => write!(f, "stop-circle"),
            Self::IconNameStop => write!(f, "stop"),
            Self::IconNameStopwatch => write!(f, "stopwatch"),
            Self::IconNameStorefront => write!(f, "storefront"),
            Self::IconNameSubway => write!(f, "subway"),
            Self::IconNameSunny => write!(f, "sunny"),
            Self::IconNameSwapHorizontal => write!(f, "swap-horizontal"),
            Self::IconNameSwapVertical => write!(f, "swap-vertical"),
            Self::IconNameSyncCircle => write!(f, "sync-circle"),
            Self::IconNameSync => write!(f, "sync"),
            Self::IconNameTabletLandscape => write!(f, "t.txt"),
            Self::IconNameTabletPortrait => write!(f, "tablet-landscape"),
            Self::IconNameTelescope => write!(f, "tablet-portrait"),
            Self::IconNameTennisball => write!(f, "telescope"),
            Self::IconNameTerminal => write!(f, "tennisball"),
            Self::IconNameText => write!(f, "terminal"),
            Self::IconNameThermometer => write!(f, "text"),
            Self::IconNameThumbsDown => write!(f, "thermometer"),
            Self::IconNameThumbsUp => write!(f, "thumbs-down"),
            Self::IconNameThunderstorm => write!(f, "thumbs-up"),
            Self::IconNameTicket => write!(f, "thunderstorm"),
            Self::IconNameTime => write!(f, "ticket"),
            Self::IconNameTimer => write!(f, "time"),
            Self::IconNameToday => write!(f, "timer"),
            Self::IconNameToggle => write!(f, "today"),
            Self::IconNameTrailSign => write!(f, "toggle"),
            Self::IconNameTrain => write!(f, "trail-sign"),
            Self::IconNameTransgender => write!(f, "train"),
            Self::IconNameTrashBin => write!(f, "transgender"),
            Self::IconNameTrash => write!(f, "trash-bin"),
            Self::IconNameTrendingDown => write!(f, "trash"),
            Self::IconNameTrendingUp => write!(f, "trending-down"),
            Self::IconNameTriangle => write!(f, "trending-up"),
            Self::IconNameTrophy => write!(f, "triangle"),
            Self::IconNameTv => write!(f, "trophy"),
            Self::IconNameUmbrella => write!(f, "tv"),
            Self::IconNameUnlink => write!(f, "umbrella"),
            Self::IconNameVideocamOff => write!(f, "unlink"),
            Self::IconNameVideocam => write!(f, "videocam-off"),
            Self::IconNameVolumeHigh => write!(f, "videocam"),
            Self::IconNameVolumeLow => write!(f, "volume-high"),
            Self::IconNameVolumeMedium => write!(f, "volume-low"),
            Self::IconNameVolumeMute => write!(f, "volume-medium"),
            Self::IconNameVolumeOff => write!(f, "volume-mute"),
            Self::IconNameWalk => write!(f, "volume-off"),
            Self::IconNameWallet => write!(f, "walk"),
            Self::IconNameWarning => write!(f, "wallet"),
            Self::IconNameWatch => write!(f, "warning"),
            Self::IconNameWater => write!(f, "watch"),
            Self::IconNameWifi => write!(f, "water"),
            Self::IconNameWine => write!(f, "wifi"),
            Self::IconNameWoman => write!(f, "wine"),
            Self::Woman => write!(f, "woman"),
        }
    }
}

impl Default for ApimodelPeriodIconName {
    fn default() -> ApimodelPeriodIconName {
        Self::IconNameAccessibility
    }
}

