/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "format")]
pub enum ApimodelPropertyWithValue {
    #[serde(rename="text")]
    Text(Box<models::ApimodelTextPropertyValue>),
    #[serde(rename="number")]
    Number(Box<models::ApimodelNumberPropertyValue>),
    #[serde(rename="select")]
    Select(Box<models::ApimodelSelectPropertyValue>),
    #[serde(rename="multi_select")]
    MultiSelect(Box<models::ApimodelMultiSelectPropertyValue>),
    #[serde(rename="date")]
    Date(Box<models::ApimodelDatePropertyValue>),
    #[serde(rename="files")]
    Files(Box<models::ApimodelFilesPropertyValue>),
    #[serde(rename="checkbox")]
    Checkbox(Box<models::ApimodelCheckboxPropertyValue>),
    #[serde(rename="url")]
    Url(Box<models::ApimodelUrlPropertyValue>),
    #[serde(rename="email")]
    Email(Box<models::ApimodelEmailPropertyValue>),
    #[serde(rename="phone")]
    Phone(Box<models::ApimodelPhonePropertyValue>),
    #[serde(rename="objects")]
    Objects(Box<models::ApimodelObjectsPropertyValue>),
}

impl Default for ApimodelPropertyWithValue {
    fn default() -> Self {
        Self::Text(Default::default())
    }
}


