/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelNamedIcon {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::ApimodelColor>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::ApimodelIconFormat>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<models::ApimodelIconName>,
}

impl ApimodelNamedIcon {
    pub fn new() -> ApimodelNamedIcon {
        ApimodelNamedIcon {
            color: None,
            format: None,
            name: None,
        }
    }
}

