/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelPropertyLinkWithValue {
    ApimodelTextPropertyLinkValue(Box<models::ApimodelTextPropertyLinkValue>),
    ApimodelNumberPropertyLinkValue(Box<models::ApimodelNumberPropertyLinkValue>),
    ApimodelSelectPropertyLinkValue(Box<models::ApimodelSelectPropertyLinkValue>),
    ApimodelMultiSelectPropertyLinkValue(Box<models::ApimodelMultiSelectPropertyLinkValue>),
    ApimodelDatePropertyLinkValue(Box<models::ApimodelDatePropertyLinkValue>),
    ApimodelFilesPropertyLinkValue(Box<models::ApimodelFilesPropertyLinkValue>),
    ApimodelCheckboxPropertyLinkValue(Box<models::ApimodelCheckboxPropertyLinkValue>),
    ApimodelUrlPropertyLinkValue(Box<models::ApimodelUrlPropertyLinkValue>),
    ApimodelEmailPropertyLinkValue(Box<models::ApimodelEmailPropertyLinkValue>),
    ApimodelPhonePropertyLinkValue(Box<models::ApimodelPhonePropertyLinkValue>),
    ApimodelObjectsPropertyLinkValue(Box<models::ApimodelObjectsPropertyLinkValue>),
}

impl Default for ApimodelPropertyLinkWithValue {
    fn default() -> Self {
        Self::ApimodelTextPropertyLinkValue(Default::default())
    }
}

