/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelIcon : The icon of the object, or null if the object has no icon
/// The icon of the object, or null if the object has no icon
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelIcon {
    ApimodelEmojiIcon(Box<models::ApimodelEmojiIcon>),
    ApimodelFileIcon(Box<models::ApimodelFileIcon>),
    ApimodelNamedIcon(Box<models::ApimodelNamedIcon>),
}

impl Default for ApimodelIcon {
    fn default() -> Self {
        Self::ApimodelEmojiIcon(Default::default())
    }
}

