/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodCreateSpaceRequest {
    /// The description of the space
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The name of the space
    #[serde(rename = "name")]
    pub name: String,
}

impl ApimodelPeriodCreateSpaceRequest {
    pub fn new(name: String) -> ApimodelPeriodCreateSpaceRequest {
        ApimodelPeriodCreateSpaceRequest {
            description: None,
            name,
        }
    }
}

