/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodCreateTagRequest {
    #[serde(rename = "color")]
    pub color: models::ApimodelPeriodColor,
    /// The name of the tag
    #[serde(rename = "name")]
    pub name: String,
}

impl ApimodelPeriodCreateTagRequest {
    pub fn new(color: models::ApimodelPeriodColor, name: String) -> ApimodelPeriodCreateTagRequest {
        ApimodelPeriodCreateTagRequest {
            color,
            name,
        }
    }
}

