/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelSortOptions : The sorting options for the search results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelSortOptions {
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<models::ApimodelSortDirection>,
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<models::ApimodelSortProperty>,
}

impl ApimodelSortOptions {
    /// The sorting options for the search results
    pub fn new() -> ApimodelSortOptions {
        ApimodelSortOptions {
            direction: None,
            property_key: None,
        }
    }
}

