/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPropertyResponse {
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Box<models::ApimodelProperty>>,
}

impl ApimodelPropertyResponse {
    pub fn new() -> ApimodelPropertyResponse {
        ApimodelPropertyResponse {
            property: None,
        }
    }
}

