/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelMultiSelectPropertyValue {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::ApimodelPropertyFormat>,
    /// The id of the property
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The key of the property
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The selected tag values of the property
    #[serde(rename = "multi_select", skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<Vec<models::ApimodelTag>>,
    /// The name of the property
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The data model of the object
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
}

impl ApimodelMultiSelectPropertyValue {
    pub fn new() -> ApimodelMultiSelectPropertyValue {
        ApimodelMultiSelectPropertyValue {
            format: None,
            id: None,
            key: None,
            multi_select: None,
            name: None,
            object: None,
        }
    }
}

