/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationPaginatedResponseApimodelObject {
    /// The list of items in the current result set
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::ApimodelObject>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationPaginationMeta>>,
}

impl PaginationPaginatedResponseApimodelObject {
    pub fn new() -> PaginationPaginatedResponseApimodelObject {
        PaginationPaginatedResponseApimodelObject {
            data: None,
            pagination: None,
        }
    }
}

