/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTypeError {
    Status400(models::UtilValidationError),
    Status401(models::UtilUnauthorizedError),
    Status429(models::UtilRateLimitError),
    Status500(models::UtilServerError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTypeError {
    Status401(models::UtilUnauthorizedError),
    Status403(models::UtilForbiddenError),
    Status404(models::UtilNotFoundError),
    Status410(models::UtilGoneError),
    Status429(models::UtilRateLimitError),
    Status500(models::UtilServerError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTypeError {
    Status401(models::UtilUnauthorizedError),
    Status404(models::UtilNotFoundError),
    Status410(models::UtilGoneError),
    Status500(models::UtilServerError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_types`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTypesError {
    Status401(models::UtilUnauthorizedError),
    Status500(models::UtilServerError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTypeError {
    Status400(models::UtilValidationError),
    Status401(models::UtilUnauthorizedError),
    Status404(models::UtilNotFoundError),
    Status410(models::UtilGoneError),
    Status429(models::UtilRateLimitError),
    Status500(models::UtilServerError),
    UnknownValue(serde_json::Value),
}


/// Creates a new type in the specified space using a JSON payload. The creation process is subject to rate limiting. The payload must include type details such as the name, icon, and layout. The endpoint then returns the full type data, ready to be used for creating objects.
pub async fn create_type(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, apimodel_create_type_request: models::ApimodelCreateTypeRequest) -> Result<models::ApimodelTypeResponse, Error<CreateTypeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_body_apimodel_create_type_request = apimodel_create_type_request;

    let uri_str = format!("{}/v1/spaces/{space_id}/types", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_apimodel_create_type_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApimodelTypeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApimodelTypeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint “deletes” an type by marking it as archived. The deletion process is performed safely and is subject to rate limiting. It returns the type’s details after it has been archived. Proper error handling is in place for situations such as when the type isn’t found or the deletion cannot be performed because of permission issues.
pub async fn delete_type(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, type_id: &str) -> Result<models::ApimodelTypeResponse, Error<DeleteTypeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_path_type_id = type_id;

    let uri_str = format!("{}/v1/spaces/{space_id}/types/{type_id}", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id), type_id=crate::apis::urlencode(p_path_type_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApimodelTypeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApimodelTypeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches detailed information about one specific type by its ID. This includes the type’s unique key, name, icon, and layout. This detailed view assists clients in understanding the expected structure and style for objects of that type and in guiding the user interface (such as displaying appropriate icons or layout hints).
pub async fn get_type(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, type_id: &str) -> Result<models::ApimodelTypeResponse, Error<GetTypeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_path_type_id = type_id;

    let uri_str = format!("{}/v1/spaces/{space_id}/types/{type_id}", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id), type_id=crate::apis::urlencode(p_path_type_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApimodelTypeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApimodelTypeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint retrieves a paginated list of types (e.g. 'Page', 'Note', 'Task') available within the specified space. Each type’s record includes its unique identifier, type key, display name, icon, and layout. While a type's id is truly unique, a type's key can be the same across spaces for known types, e.g. 'page' for 'Page'. Clients use this information when offering choices for object creation or for filtering objects by type through search.
pub async fn list_types(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, offset: Option<i32>, limit: Option<i32>) -> Result<models::PaginationPaginatedResponseApimodelType, Error<ListTypesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_query_offset = offset;
    let p_query_limit = limit;

    let uri_str = format!("{}/v1/spaces/{space_id}/types", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginationPaginatedResponseApimodelType`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PaginationPaginatedResponseApimodelType`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTypesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint updates an existing type in the specified space using a JSON payload. The update process is subject to rate limiting. The payload must include the name and properties to be updated. The endpoint then returns the full type data, ready for further interactions.
pub async fn update_type(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, type_id: &str, apimodel_update_type_request: models::ApimodelUpdateTypeRequest) -> Result<models::ApimodelTypeResponse, Error<UpdateTypeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_path_type_id = type_id;
    let p_body_apimodel_update_type_request = apimodel_update_type_request;

    let uri_str = format!("{}/v1/spaces/{space_id}/types/{type_id}", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id), type_id=crate::apis::urlencode(p_path_type_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_apimodel_update_type_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ApimodelTypeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ApimodelTypeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

