/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodTemplateResponse {
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::ApimodelPeriodObjectWithBody>>,
}

impl ApimodelPeriodTemplateResponse {
    pub fn new() -> ApimodelPeriodTemplateResponse {
        ApimodelPeriodTemplateResponse {
            template: None,
        }
    }
}

