/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelPeriodPropertyWithValue {
    ApimodelPeriodTextPropertyValue(Box<models::ApimodelPeriodTextPropertyValue>),
    ApimodelPeriodNumberPropertyValue(Box<models::ApimodelPeriodNumberPropertyValue>),
    ApimodelPeriodSelectPropertyValue(Box<models::ApimodelPeriodSelectPropertyValue>),
    ApimodelPeriodMultiSelectPropertyValue(Box<models::ApimodelPeriodMultiSelectPropertyValue>),
    ApimodelPeriodDatePropertyValue(Box<models::ApimodelPeriodDatePropertyValue>),
    ApimodelPeriodFilesPropertyValue(Box<models::ApimodelPeriodFilesPropertyValue>),
    ApimodelPeriodCheckboxPropertyValue(Box<models::ApimodelPeriodCheckboxPropertyValue>),
    ApimodelPeriodUrlPropertyValue(Box<models::ApimodelPeriodUrlPropertyValue>),
    ApimodelPeriodEmailPropertyValue(Box<models::ApimodelPeriodEmailPropertyValue>),
    ApimodelPeriodPhonePropertyValue(Box<models::ApimodelPeriodPhonePropertyValue>),
    ApimodelPeriodObjectsPropertyValue(Box<models::ApimodelPeriodObjectsPropertyValue>),
}

impl Default for ApimodelPeriodPropertyWithValue {
    fn default() -> Self {
        Self::ApimodelPeriodTextPropertyValue(Default::default())
    }
}

