/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodUpdateTagRequest {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::ApimodelPeriodColor>,
    /// The name to set for the tag
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ApimodelPeriodUpdateTagRequest {
    pub fn new() -> ApimodelPeriodUpdateTagRequest {
        ApimodelPeriodUpdateTagRequest {
            color: None,
            name: None,
        }
    }
}

