/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodMultiSelectPropertyLinkValue {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The selected tag ids of the property; see ListTags endpoint for valid values
    #[serde(rename = "multi_select", skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<Vec<String>>,
}

impl ApimodelPeriodMultiSelectPropertyLinkValue {
    pub fn new() -> ApimodelPeriodMultiSelectPropertyLinkValue {
        ApimodelPeriodMultiSelectPropertyLinkValue {
            key: None,
            multi_select: None,
        }
    }
}

