/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelPeriodSortOptions : The sorting options for the search results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApimodelPeriodSortOptions {
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<models::ApimodelPeriodSortDirection>,
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<models::ApimodelPeriodSortProperty>,
}

impl ApimodelPeriodSortOptions {
    /// The sorting options for the search results
    pub fn new() -> ApimodelPeriodSortOptions {
        ApimodelPeriodSortOptions {
            direction: None,
            property_key: None,
        }
    }
}

