/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-05-20
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApimodelPeriodIcon : The icon of the object, or null if the object has no icon
/// The icon of the object, or null if the object has no icon
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApimodelPeriodIcon {
    ApimodelPeriodEmojiIcon(Box<models::ApimodelPeriodEmojiIcon>),
    ApimodelPeriodFileIcon(Box<models::ApimodelPeriodFileIcon>),
    ApimodelPeriodNamedIcon(Box<models::ApimodelPeriodNamedIcon>),
}

impl Default for ApimodelPeriodIcon {
    fn default() -> Self {
        Self::ApimodelPeriodEmojiIcon(Default::default())
    }
}

