/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_template`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTemplateError {
    Status401(models::UnauthorizedError),
    Status404(models::NotFoundError),
    Status410(models::GoneError),
    Status500(models::ServerError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_templates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTemplatesError {
    Status401(models::UnauthorizedError),
    Status500(models::ServerError),
    UnknownValue(serde_json::Value),
}


/// Fetches full details for one template associated with a particular type in a space. The response provides the template’s identifier, name, icon, and any other relevant metadata. This endpoint is useful when a client needs to preview or apply a template to prefill object creation fields.
pub async fn get_template(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, type_id: &str, template_id: &str) -> Result<models::TemplateResponse, Error<GetTemplateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_path_type_id = type_id;
    let p_path_template_id = template_id;

    let uri_str = format!("{}/v1/spaces/{space_id}/types/{type_id}/templates/{template_id}", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id), type_id=crate::apis::urlencode(p_path_type_id), template_id=crate::apis::urlencode(p_path_template_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TemplateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TemplateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTemplateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint returns a paginated list of templates that are associated with a specific type within a space. Templates provide pre‑configured structures for creating new objects. Each template record contains its identifier, name, and icon, so that clients can offer users a selection of templates when creating objects. Supports dynamic filtering via query parameters (e.g., ?name[contains]=invoice). See FilterCondition enum for available conditions.
pub async fn list_templates(configuration: &configuration::Configuration, anytype_version: &str, space_id: &str, type_id: &str, offset: Option<i32>, limit: Option<i32>) -> Result<models::PaginatedResponseObject, Error<ListTemplatesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_anytype_version = anytype_version;
    let p_path_space_id = space_id;
    let p_path_type_id = type_id;
    let p_query_offset = offset;
    let p_query_limit = limit;

    let uri_str = format!("{}/v1/spaces/{space_id}/types/{type_id}/templates", configuration.base_path, space_id=crate::apis::urlencode(p_path_space_id), type_id=crate::apis::urlencode(p_path_type_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Anytype-Version", p_header_anytype_version.to_string());
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginatedResponseObject`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PaginatedResponseObject`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTemplatesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

