/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTagRequest {
    #[serde(rename = "color")]
    pub color: models::Color,
    /// The optional custom key for the tag
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The name of the tag
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateTagRequest {
    pub fn new(color: models::Color, name: String) -> CreateTagRequest {
        CreateTagRequest {
            color,
            key: None,
            name,
        }
    }
}

