/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePropertyRequest {
    #[serde(rename = "format")]
    pub format: models::PropertyFormat,
    /// The key of the property; should always be snake_case, otherwise it will be converted to snake_case
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The name of the property
    #[serde(rename = "name")]
    pub name: String,
    /// Tags to create for select/multi_select properties
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::CreateTagRequest>>,
}

impl CreatePropertyRequest {
    pub fn new(format: models::PropertyFormat, name: String) -> CreatePropertyRequest {
        CreatePropertyRequest {
            format,
            key: None,
            name,
            tags: None,
        }
    }
}

