/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Filter {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<models::FilterCondition>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::PropertyFormat>,
    /// The id of the filter
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The property key used for filtering
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<String>,
    /// The value used for filtering
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl Filter {
    pub fn new() -> Filter {
        Filter {
            condition: None,
            format: None,
            id: None,
            property_key: None,
            value: None,
        }
    }
}

