/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterOperator : Logical operator for combining filters (and, or)
/// Logical operator for combining filters (and, or)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterOperator {
    #[serde(rename = "and")]
    FilterOperatorAnd,
    #[serde(rename = "or")]
    FilterOperatorOr,

}

impl std::fmt::Display for FilterOperator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FilterOperatorAnd => write!(f, "and"),
            Self::FilterOperatorOr => write!(f, "or"),
        }
    }
}

impl Default for FilterOperator {
    fn default() -> FilterOperator {
        Self::FilterOperatorAnd
    }
}

