/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FilterItem {
    TextFilterItem(Box<models::TextFilterItem>),
    NumberFilterItem(Box<models::NumberFilterItem>),
    SelectFilterItem(Box<models::SelectFilterItem>),
    MultiSelectFilterItem(Box<models::MultiSelectFilterItem>),
    DateFilterItem(Box<models::DateFilterItem>),
    CheckboxFilterItem(Box<models::CheckboxFilterItem>),
    FilesFilterItem(Box<models::FilesFilterItem>),
    UrlFilterItem(Box<models::UrlFilterItem>),
    EmailFilterItem(Box<models::EmailFilterItem>),
    PhoneFilterItem(Box<models::PhoneFilterItem>),
    ObjectsFilterItem(Box<models::ObjectsFilterItem>),
    EmptyFilterItem(Box<models::EmptyFilterItem>),
}

impl Default for FilterItem {
    fn default() -> Self {
        Self::TextFilterItem(Default::default())
    }
}

