/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterCondition : The filter condition
/// The filter condition
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterCondition {
    #[serde(rename = "eq")]
    FilterConditionEq,
    #[serde(rename = "ne")]
    FilterConditionNe,
    #[serde(rename = "gt")]
    FilterConditionGt,
    #[serde(rename = "gte")]
    FilterConditionGte,
    #[serde(rename = "lt")]
    FilterConditionLt,
    #[serde(rename = "lte")]
    FilterConditionLte,
    #[serde(rename = "contains")]
    FilterConditionContains,
    #[serde(rename = "ncontains")]
    FilterConditionNContains,
    #[serde(rename = "in")]
    FilterConditionIn,
    #[serde(rename = "nin")]
    FilterConditionNin,
    #[serde(rename = "all")]
    FilterConditionAll,
    #[serde(rename = "empty")]
    FilterConditionEmpty,
    #[serde(rename = "nempty")]
    FilterConditionNEmpty,

}

impl std::fmt::Display for FilterCondition {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FilterConditionEq => write!(f, "eq"),
            Self::FilterConditionNe => write!(f, "ne"),
            Self::FilterConditionGt => write!(f, "gt"),
            Self::FilterConditionGte => write!(f, "gte"),
            Self::FilterConditionLt => write!(f, "lt"),
            Self::FilterConditionLte => write!(f, "lte"),
            Self::FilterConditionContains => write!(f, "contains"),
            Self::FilterConditionNContains => write!(f, "ncontains"),
            Self::FilterConditionIn => write!(f, "in"),
            Self::FilterConditionNin => write!(f, "nin"),
            Self::FilterConditionAll => write!(f, "all"),
            Self::FilterConditionEmpty => write!(f, "empty"),
            Self::FilterConditionNEmpty => write!(f, "nempty"),
        }
    }
}

impl Default for FilterCondition {
    fn default() -> FilterCondition {
        Self::FilterConditionEq
    }
}

