/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterExpression : Expression filter with nested AND/OR conditions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterExpression {
    /// List of format-specific filter conditions
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::FilterItem>>,
    /// Nested filter expressions for complex logic
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::FilterExpression>>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<models::FilterOperator>,
}

impl FilterExpression {
    /// Expression filter with nested AND/OR conditions
    pub fn new() -> FilterExpression {
        FilterExpression {
            conditions: None,
            filters: None,
            operator: None,
        }
    }
}

