/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Icon : The icon of the object, or null if the object has no icon
/// The icon of the object, or null if the object has no icon
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Icon {
    EmojiIcon(Box<models::EmojiIcon>),
    FileIcon(Box<models::FileIcon>),
    NamedIcon(Box<models::NamedIcon>),
}

impl Default for Icon {
    fn default() -> Self {
        Self::EmojiIcon(Default::default())
    }
}

