/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiSelectFilterItem {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<models::FilterCondition>,
    /// The tag IDs to filter by
    #[serde(rename = "multi_select", skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<Vec<String>>,
    /// The property key to filter on
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<String>,
}

impl MultiSelectFilterItem {
    pub fn new() -> MultiSelectFilterItem {
        MultiSelectFilterItem {
            condition: None,
            multi_select: None,
            property_key: None,
        }
    }
}

