/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiSelectPropertyLinkValue {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The selected tags (by key, e.g., \"important\", or ID, e.g., \"bafyrei...\") of the property; see ListTags endpoint for valid values
    #[serde(rename = "multi_select", skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<Vec<String>>,
}

impl MultiSelectPropertyLinkValue {
    pub fn new() -> MultiSelectPropertyLinkValue {
        MultiSelectPropertyLinkValue {
            key: None,
            multi_select: None,
        }
    }
}

