/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamedIcon {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::Color>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::IconFormat>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<models::IconName>,
}

impl NamedIcon {
    pub fn new() -> NamedIcon {
        NamedIcon {
            color: None,
            format: None,
            name: None,
        }
    }
}

