/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NumberPropertyLinkValue {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The number value of the property
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<f64>,
}

impl NumberPropertyLinkValue {
    pub fn new() -> NumberPropertyLinkValue {
        NumberPropertyLinkValue {
            key: None,
            number: None,
        }
    }
}

