/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PropertyLinkWithValue {
    TextPropertyLinkValue(Box<models::TextPropertyLinkValue>),
    NumberPropertyLinkValue(Box<models::NumberPropertyLinkValue>),
    SelectPropertyLinkValue(Box<models::SelectPropertyLinkValue>),
    MultiSelectPropertyLinkValue(Box<models::MultiSelectPropertyLinkValue>),
    DatePropertyLinkValue(Box<models::DatePropertyLinkValue>),
    FilesPropertyLinkValue(Box<models::FilesPropertyLinkValue>),
    CheckboxPropertyLinkValue(Box<models::CheckboxPropertyLinkValue>),
    UrlPropertyLinkValue(Box<models::UrlPropertyLinkValue>),
    EmailPropertyLinkValue(Box<models::EmailPropertyLinkValue>),
    PhonePropertyLinkValue(Box<models::PhonePropertyLinkValue>),
    ObjectsPropertyLinkValue(Box<models::ObjectsPropertyLinkValue>),
}

impl Default for PropertyLinkWithValue {
    fn default() -> Self {
        Self::TextPropertyLinkValue(Default::default())
    }
}

