/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropertyResponse {
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Box<models::Property>>,
}

impl PropertyResponse {
    pub fn new() -> PropertyResponse {
        PropertyResponse {
            property: None,
        }
    }
}

