/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Property : The property
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Property {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::PropertyFormat>,
    /// The id of the property
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The key of the property
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The name of the property
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The data model of the object
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
}

impl Property {
    /// The property
    pub fn new() -> Property {
        Property {
            format: None,
            id: None,
            key: None,
            name: None,
            object: None,
        }
    }
}

