/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropertyLink {
    #[serde(rename = "format")]
    pub format: models::PropertyFormat,
    /// The key of the property
    #[serde(rename = "key")]
    pub key: String,
    /// The name of the property
    #[serde(rename = "name")]
    pub name: String,
}

impl PropertyLink {
    pub fn new(format: models::PropertyFormat, key: String, name: String) -> PropertyLink {
        PropertyLink {
            format,
            key,
            name,
        }
    }
}

