/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "format")]
pub enum PropertyWithValue {
    #[serde(rename="text")]
    Text(Box<models::TextPropertyValue>),
    #[serde(rename="number")]
    Number(Box<models::NumberPropertyValue>),
    #[serde(rename="select")]
    Select(Box<models::SelectPropertyValue>),
    #[serde(rename="multi_select")]
    MultiSelect(Box<models::MultiSelectPropertyValue>),
    #[serde(rename="date")]
    Date(Box<models::DatePropertyValue>),
    #[serde(rename="files")]
    Files(Box<models::FilesPropertyValue>),
    #[serde(rename="checkbox")]
    Checkbox(Box<models::CheckboxPropertyValue>),
    #[serde(rename="url")]
    Url(Box<models::UrlPropertyValue>),
    #[serde(rename="email")]
    Email(Box<models::EmailPropertyValue>),
    #[serde(rename="phone")]
    Phone(Box<models::PhonePropertyValue>),
    #[serde(rename="objects")]
    Objects(Box<models::ObjectsPropertyValue>),
}

impl Default for PropertyWithValue {
    fn default() -> Self {
        Self::Text(Default::default())
    }
}


