/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectPropertyLinkValue {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The selected tag (by key, e.g., \"important\", or ID, e.g., \"bafyrei...\") of the property; see ListTags endpoint for valid values
    #[serde(rename = "select", skip_serializing_if = "Option::is_none")]
    pub select: Option<String>,
}

impl SelectPropertyLinkValue {
    pub fn new() -> SelectPropertyLinkValue {
        SelectPropertyLinkValue {
            key: None,
            select: None,
        }
    }
}

