/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectFilterItem {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<models::FilterCondition>,
    /// The property key to filter on
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<String>,
    /// Tag Id - for eq/ne conditions (single selection)
    #[serde(rename = "select", skip_serializing_if = "Option::is_none")]
    pub select: Option<String>,
}

impl SelectFilterItem {
    pub fn new() -> SelectFilterItem {
        SelectFilterItem {
            condition: None,
            property_key: None,
            select: None,
        }
    }
}

