/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SortOptions : The sorting options for the search results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortOptions {
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<models::SortDirection>,
    #[serde(rename = "property_key", skip_serializing_if = "Option::is_none")]
    pub property_key: Option<models::SortProperty>,
}

impl SortOptions {
    /// The sorting options for the search results
    pub fn new() -> SortOptions {
        SortOptions {
            direction: None,
            property_key: None,
        }
    }
}

