/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Space : The space
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Space {
    /// The description of the space
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The gateway url to serve files and media
    #[serde(rename = "gateway_url", skip_serializing_if = "Option::is_none")]
    pub gateway_url: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Box<models::Icon>>,
    /// The id of the space
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the space
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The network id of the space
    #[serde(rename = "network_id", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<String>,
    /// The data model of the object
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
}

impl Space {
    /// The space
    pub fn new() -> Space {
        Space {
            description: None,
            gateway_url: None,
            icon: None,
            id: None,
            name: None,
            network_id: None,
            object: None,
        }
    }
}
/// The data model of the object
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "space")]
    Space,
    #[serde(rename = "chat")]
    Chat,
}

impl Default for Object {
    fn default() -> Object {
        Self::Space
    }
}

