/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpaceResponse {
    #[serde(rename = "space", skip_serializing_if = "Option::is_none")]
    pub space: Option<Box<models::Space>>,
}

impl SpaceResponse {
    pub fn new() -> SpaceResponse {
        SpaceResponse {
            space: None,
        }
    }
}

