/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTypeRequest {
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Box<models::Icon>>,
    /// The key to set for the type; should always be snake_case, otherwise it will be converted to snake_case
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<models::TypeLayout>,
    /// The name to set for the type
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The plural name to set for the type
    #[serde(rename = "plural_name", skip_serializing_if = "Option::is_none")]
    pub plural_name: Option<String>,
    /// The properties to set for the type
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<models::PropertyLink>>,
}

impl UpdateTypeRequest {
    pub fn new() -> UpdateTypeRequest {
        UpdateTypeRequest {
            icon: None,
            key: None,
            layout: None,
            name: None,
            plural_name: None,
            properties: None,
        }
    }
}

