/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTagRequest {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::Color>,
    /// The key to set for the tag
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The name to set for the tag
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateTagRequest {
    pub fn new() -> UpdateTagRequest {
        UpdateTagRequest {
            color: None,
            key: None,
            name: None,
        }
    }
}

