/*
 * Anytype API
 *
 * This API enables seamless interaction with Anytype's resources - spaces, objects, properties, types, templates, and beyond.
 *
 * The version of the OpenAPI document: 2025-11-08
 * Contact: support@anytype.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateObjectRequest {
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Box<models::Icon>>,
    /// The updated body of the object
    #[serde(rename = "markdown", skip_serializing_if = "Option::is_none")]
    pub markdown: Option<String>,
    /// The name of the object
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The properties to set for the object; see ListTypes or GetType endpoints for linked properties
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<models::PropertyLinkWithValue>>,
    /// The key of the type of object to set
    #[serde(rename = "type_key", skip_serializing_if = "Option::is_none")]
    pub type_key: Option<String>,
}

impl UpdateObjectRequest {
    pub fn new() -> UpdateObjectRequest {
        UpdateObjectRequest {
            icon: None,
            markdown: None,
            name: None,
            properties: None,
            type_key: None,
        }
    }
}

